"""
pypdfpatra.user_agent
~~~~~~~~~~~~~~~~~~~~
W3C Specification / HTML5 Standard: Default User-Agent style sheets.
PyPDFPatra follows the WebKit/Chrome industry-standard default stylesheet
to ensure HTML renders exactly as users expect it to in a modern browser.
"""

USER_AGENT_STYLES = {
    # Non-rendered elements
    "head": {"display": "none"},
    "style": {"display": "none"},
    "script": {"display": "none"},
    "title": {"display": "none"},
    "meta": {"display": "none"},
    "link": {"display": "none"},
    "param": {"display": "none"},
    # Block formatting defaults
    "html": {"display": "block"},
    "body": {"display": "block", "margin": "8px"},
    "div": {"display": "block"},
    "p": {"display": "block", "margin-top": "1em", "margin-bottom": "1em"},
    "blockquote": {
        "display": "block",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "margin-left": "40px",
        "margin-right": "40px",
    },
    "figure": {
        "display": "block",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "margin-left": "40px",
        "margin-right": "40px",
    },
    "pre": {
        "display": "block",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "font-family": "monospace",
        "white-space": "pre",
    },
    "hr": {
        "display": "block",
        "margin-top": "0.5em",
        "margin-bottom": "0.5em",
        "border-top-width": "1px",
        "border-top-style": "solid",
        "border-top-color": "#808080",
        "height": "0px",
    },
    # Headings
    "h1": {
        "display": "block",
        "font-size": "2em",
        "margin-top": "0.67em",
        "margin-bottom": "0.67em",
        "font-weight": "bold",
    },
    "h2": {
        "display": "block",
        "font-size": "1.5em",
        "margin-top": "0.83em",
        "margin-bottom": "0.83em",
        "font-weight": "bold",
    },
    "h3": {
        "display": "block",
        "font-size": "1.17em",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "font-weight": "bold",
    },
    "h4": {
        "display": "block",
        "font-size": "1em",
        "margin-top": "1.33em",
        "margin-bottom": "1.33em",
        "font-weight": "bold",
    },
    "h5": {
        "display": "block",
        "font-size": "0.83em",
        "margin-top": "1.67em",
        "margin-bottom": "1.67em",
        "font-weight": "bold",
    },
    "h6": {
        "display": "block",
        "font-size": "0.67em",
        "margin-top": "2.33em",
        "margin-bottom": "2.33em",
        "font-weight": "bold",
    },
    # Text decoration inline elements
    "del": {"display": "inline", "text-decoration": "line-through"},
    "s": {"display": "inline", "text-decoration": "line-through"},
    "strike": {"display": "inline", "text-decoration": "line-through"},
    "ins": {"display": "inline", "text-decoration": "underline"},
    "u": {"display": "inline", "text-decoration": "underline"},
    "a": {"display": "inline", "color": "#0000EE", "text-decoration": "underline"},
    # Lists
    "ul": {
        "display": "block",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "padding-left": "40px",
        "list-style-type": "disc",
    },
    "ol": {
        "display": "block",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "padding-left": "40px",
        "list-style-type": "decimal",
    },
    "menu": {
        "display": "block",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "padding-left": "40px",
    },
    "dir": {
        "display": "block",
        "margin-top": "1em",
        "margin-bottom": "1em",
        "padding-left": "40px",
    },
    "dl": {"display": "block", "margin-top": "1em", "margin-bottom": "1em"},
    "dd": {"display": "block", "margin-left": "40px"},
    "li": {"display": "list-item"},
    # Tables
    "table": {
        "display": "table",
        "margin-top": "0px",
        "margin-bottom": "0px",
        "border-collapse": "separate",
        "border-spacing": "2px",
    },
    "thead": {"display": "table-header-group"},
    "tbody": {"display": "table-row-group"},
    "tfoot": {"display": "table-footer-group"},
    "tr": {"display": "table-row"},
    "td": {"display": "table-cell"},
    "th": {"display": "table-cell", "font-weight": "bold", "text-align": "center"},
    "caption": {"display": "block", "text-align": "center"},
    # Forms
    "form": {"display": "block", "margin-top": "0em"},
    "fieldset": {
        "display": "block",
        "margin-left": "2px",
        "margin-right": "2px",
        "padding-top": "0.35em",
        "padding-bottom": "0.625em",
        "padding-left": "0.75em",
        "padding-right": "0.75em",
        "border": "2px solid #c0c0c0",
    },
    "legend": {"display": "block"},
    "input": {
        "display": "inline-block",
        "padding": "1px 2px",
        "border": "2px inset #ffffff",
        "background-color": "#ffffff",
    },
    "button": {
        "display": "inline-block",
        "padding": "1px 6px",
        "border": "2px outset #f0f0f0",
        "background-color": "#f0f0f0",
        "text-align": "center",
    },
    "textarea": {
        "display": "inline-block",
        "padding": "2px",
        "border": "1px solid #767676",
        "background-color": "#ffffff",
    },
    # Inline formatting defaults
    "span": {"display": "inline"},
    "b": {"display": "inline", "font-weight": "bold"},
    "strong": {"display": "inline", "font-weight": "bold"},
    "i": {"display": "inline", "font-style": "italic"},
    "em": {"display": "inline", "font-style": "italic"},
    "cite": {"display": "inline", "font-style": "italic"},
    "var": {"display": "inline", "font-style": "italic"},
    "address": {"display": "block", "font-style": "italic"},
    "aside": {"display": "block"},
    "footer": {"display": "block"},
    "header": {"display": "block"},
    "section": {"display": "block"},
    "nav": {"display": "block"},
    "article": {"display": "block"},
    "main": {"display": "block"},
    "sub": {"display": "inline", "font-size": "0.83em"},
    "sup": {"display": "inline", "font-size": "0.83em"},
    "code": {"display": "inline", "font-family": "monospace"},
    "kbd": {"display": "inline", "font-family": "monospace"},
    "samp": {"display": "inline", "font-family": "monospace"},
    "img": {"display": "inline-block"},
    # Anonymous text node default wrapper
    "#text": {"display": "inline"},
}
